### PR TITLE
Open channel from change channel capacity

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Feature to  open a public channel with change from decrease channel capacity.
Let me know what you think Alex. I feel it can be done better.

Changed files:

capacity/ask_for_change_details.js
capacity/ask_for_decrease.js
capacity/assemble_replacement_tx.js
capacity/fee_for_replacement.js
capacity/get_capacity_replacement.js
capacity/propose_capacity_change.js
capacity/propose_channel_open.js (new file)

### CODE REVIEW

**Comment by alexbosworth** [comment]
Cool that you got it working - I was thinking that if you have 1 extra channel why not more, but it might be smart to start smaller

I think the missing interim pieces are:
- The regular change channel capacity needs more error handling, someone who tried it reported that the force close path left a pending channel around and I think that should ideally be cleaned up
- The RBF bump was reported as not working and that needs a test scenario to reproduce why that happened and then a resolution to fix whatever went wrong there

If these things aren't addressed the annoying thing here is that you would potentially be left with 2 pending zombie channels

**Comment by alexbosworth** [comment]
looking good, will take a look at merging

**Comment by niteshbalusu11** [comment]
Ok, cool.

**Comment by alexbosworth** [comment]
I'm reviewing it now but github wont' let it be merged because it needs to be rebased

**Pull request merged**
