### PR TITLE
Send trade to peer via p2p messaging.

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Added send option to send trade to peer directly via p2p.

Changed files: create_trade.js

Added a send function that sends a message using p2p messaging.

### CODE REVIEW

**Comment by alexbosworth** [comment]
I think the ideal for this flow is that the peer could actually ask for the trade before it's sent to them, I can work on that part

**Comment by niteshbalusu11** [comment]
> I think the ideal for this flow is that the peer could actually ask for the trade before it's sent to them, I can work on that part

Cool

**Comment by alexbosworth** [comment]
I'm still on the concept part of this, I think the trade flow for the buyer should be something like:

1. I receive a trade offer via keysend (such as a network-wide advertisement)
2. I receive a trade description out-of-band but then I have to query the offering side to get the actual trade-secret

Things to try and avoid:

- Having to worry about spam
- Building in a requirement to p2p connect

**Comment by niteshbalusu11** [comment]
Closing this PR since you're working on the V1 Trade

**Pull request closed without merging**
